### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by dimaip** [Flow-Community/Community.News#1]
We should spend some time to settle on naming conventions. 
e.g. I don't quite like `Community.News:NewsPrimaryContent`, as it reflects the methode by which the stuff gets rendered, not the meaning of it. I'd go somewhere along the lines of `NewsDetail`, `CategoryDetail`, as that's the convention from EXT:News that everyone is used to. But maybe you have a better idea?

**Comment by Weissheiten** [comment]
I settled for "[Node]PrimaryContent" because to me this was what it is: "the primary content element".
Imo this helps users understand what actually happens when extending the "case" prototype ("There is a Prototype with a case and each instance of X should have the primary content rendered as Version XPrimaryContent.)
If you want to rename this for the sake of compatibility with EXT:News we can of course consider a name change. I'd like to point out that we have a ContentCollection though where EXT:News has an RTE field, so strictly speaking users could include other things in their news that don't only HAVE to be news details. (Ads package or similar?) Though I agree that in most cases this will be the "News Details"

**Comment by dimaip** [comment]
It's not only for the sake of compatibility with EXT:News, it's for the meaning. E.g. the integrator may decide to integrate this component via root matcher, not PrimaryContent, but the element would still the same. So speaking in Domain Driven Design terminology we should name prototypes in the language of our domain -- news publishing, not in the language of Neos technical implementation. Makes sense?

Regarding ads and stuff not related to news, that would be much better to put it for integrator into different content collection and render it with different TS object, not related to News ( because that might also be rendered on other parts of the site as well, so we should not bind ads to news).

**Comment by Weissheiten** [comment]
If an Integrator would integrate the component via root matcher why would he cease to rename the template and object which he is most likely to redo then in any case?
The ads were an example of what people could possibly do with a contentcollection in this section - not a suggestion to implement that there.
The Name also fits the News Publishing Domain imo because it IS the primary content of a News entry.- but as said I don't have a problem switching to "NewsDetail" because I think the propability of people putting non-newsdetail related stuff there is small and I can see the possible confusion in naming considering your scenario.

**Comment by dimaip** [comment]
That would make sense to call it this way if we had `NewsDetail` object for rendering the whole news page and `NewsDetailPrimaryContent` and `NewsDetailSidebarContent` as subobjects.
Actually I don't mind for a compromise solution to call it `NewsDetailPrimaryContent` :) That makes sense, as if integrator would want to override the whole page object with root matcher, he could call that object `NewsDetail` and include `NewsDetailPrimaryContent` as its child. But I think this logic is not obvious from first sight.
But following this logic, we'd need to have `NewsListPrimaryContent` or smth for News archive...
So I would just have `NewsDetail`, `NewsList`, `CategoryDetail`, `CategoryList` etc. for the sake of keeping things simple.

Regarding using the root matcher, have a look at this example:

```
newsPage = Sfi.Sfi:Page {
    body {
        content.main = Sfi.News:NewsDetail
        breadcrumbMenu>
    }
}
```

**Comment by Weissheiten** [comment]
I think the main point of our argument is that we have different understandings of what a "PrimaryContent" and what "Details" are - so I'd suggest instead of doing a research on that topic we go with your naming convention as this is the one used by the extension people most widely know anyways.

**Comment by dimaip** [comment]
Thanks! Naming things is hard!
